description: Upload openapi specification site to S3
parameters:
  s3_bucket:
    type: string
  file_name:
    type: string
    description: The name of the openapi file.
  entity_name:
    type: string
    description: Name of the service

steps:
  - attach_workspace:
      at: .
  - s3/sync:
      from: build/generated/<< parameters.file_name >>
      to: >-
        s3://<< parameters.s3_bucket >>/openapi/<< parameters.entity_name >>/<< parameters.file_name >>
