description: Upload openapi specification site to S3
parameters:
  s3_bucket:
    type: string
  entity_name:
    type: string
    description: Name
    type: string
    description: the name of the openapi file.
    default: openapi-definition.yaml
steps:
  - attach_workspace:
      at: .
  - s3/sync:
      from: site
      to: >-
        s3://<< parameters.s3_bucket >>/openapi/<< parameters.entity_name >>/<< parameters.file_name >>
