description: >
 Upload OpenAPI spec to S3

executor: default

parameters:
  openapi_bucket:
    type: string
    description: Name of the S3 bucket to upload to
  entity_name:
    type: string
    description: Name of the api
  file_name:
    type: string
    description: The name of the openapi file.
    default: openapi-definition.yaml
steps:
  - upload-openapi-spec:
      s3_bucket: << parameters.openapi_bucket >>
      entity_name: << parameters.entity_name >>
      file_name: << parameters.file_name >>
